language: node_js
node_js:
- node
script:
  - npm test
notifications:
email: false
deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
    app: pure-beach-92370-production
script: 'curl https://pure-beach-92370.herokuapp.com/'
